GET http://localhost:3001/api/v1/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJmYWJpbG9jbzEyMyIsInJvbGUiOiJVU0VSIiwiZXhwIjoxNzA1MTc5NTU0LCJpYXQiOjE3MDUxNzg2NTR9.r5mKh82k7viNweOKzInt_UFUmOlW_MjNAUrIqZVRKfY

