POST https://hotel-trivoli-api.onrender.com/api/v1/auth/register
Content-Type: application/json

{
  "identification": "123456",
  "firstname": "normal",
  "lastname": "user",
  "birthday": "2024-01-13T10:59:58-05:00",
  "username": "user",
  "password": "user1"
} 
